// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/LibraryGreeter.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Library.GrpcGreeterService {
  /// <summary>
  /// The greeting service definition.
  /// </summary>
  public static partial class LibraryGreeter
  {
    static readonly string __ServiceName = "MyLibrary.Greet.LibraryGreeter";

    static readonly grpc::Marshaller<global::Library.GrpcGreeterService.LibraryHelloRequest> __Marshaller_MyLibrary_Greet_LibraryHelloRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Library.GrpcGreeterService.LibraryHelloRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Library.GrpcGreeterService.LibraryHelloReply> __Marshaller_MyLibrary_Greet_LibraryHelloReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Library.GrpcGreeterService.LibraryHelloReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Library.GrpcGreeterService.LibraryHelloRequest, global::Library.GrpcGreeterService.LibraryHelloReply> __Method_SayHello = new grpc::Method<global::Library.GrpcGreeterService.LibraryHelloRequest, global::Library.GrpcGreeterService.LibraryHelloReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_MyLibrary_Greet_LibraryHelloRequest,
        __Marshaller_MyLibrary_Greet_LibraryHelloReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Library.GrpcGreeterService.LibraryGreeterReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of LibraryGreeter</summary>
    [grpc::BindServiceMethod(typeof(LibraryGreeter), "BindService")]
    public abstract partial class LibraryGreeterBase
    {
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Library.GrpcGreeterService.LibraryHelloReply> SayHello(global::Library.GrpcGreeterService.LibraryHelloRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for LibraryGreeter</summary>
    public partial class LibraryGreeterClient : grpc::ClientBase<LibraryGreeterClient>
    {
      /// <summary>Creates a new client for LibraryGreeter</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public LibraryGreeterClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for LibraryGreeter that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public LibraryGreeterClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected LibraryGreeterClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected LibraryGreeterClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Library.GrpcGreeterService.LibraryHelloReply SayHello(global::Library.GrpcGreeterService.LibraryHelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Library.GrpcGreeterService.LibraryHelloReply SayHello(global::Library.GrpcGreeterService.LibraryHelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Library.GrpcGreeterService.LibraryHelloReply> SayHelloAsync(global::Library.GrpcGreeterService.LibraryHelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Library.GrpcGreeterService.LibraryHelloReply> SayHelloAsync(global::Library.GrpcGreeterService.LibraryHelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override LibraryGreeterClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new LibraryGreeterClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(LibraryGreeterBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHello, serviceImpl.SayHello).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, LibraryGreeterBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SayHello, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Library.GrpcGreeterService.LibraryHelloRequest, global::Library.GrpcGreeterService.LibraryHelloReply>(serviceImpl.SayHello));
    }

  }
}
#endregion
